def readDataFile(fileName: str) -> str:
    with open(fileName) as dataFile:
        return dataFile.read()

def d01_data() -> str: return readDataFile('d01_data.txt')
def d02_data() -> str: return readDataFile('d02_data.txt')
def d03_data() -> str: return readDataFile('d03_data.txt')
def d04_data() -> str: return readDataFile('d04_data.txt')
def d05_data() -> str: return readDataFile('d05_data.txt')
def d06_data() -> str: return readDataFile('d06_data.txt')
def d07_data() -> str: return readDataFile('d07_data.txt')
def d08_data() -> str: return readDataFile('d08_data.txt')
def d09_data() -> str: return readDataFile('d09_data.txt')
def d10_data() -> str: return readDataFile('d10_data.txt')
def d11_data() -> str: return readDataFile('d11_data.txt')
def d12_data() -> str: return readDataFile('d12_data.txt')
def d13_data() -> str: return readDataFile('d13_data.txt')
def d14_data() -> str: return readDataFile('d14_data.txt')
def d15_data() -> str: return readDataFile('d15_data.txt')
def d16_data() -> str: return readDataFile('d16_data.txt')
def d17_data() -> str: return readDataFile('d17_data.txt')
def d18_data() -> str: return readDataFile('d18_data.txt')
def d19_data() -> str: return readDataFile('d19_data.txt')
def d20_data() -> str: return readDataFile('d20_data.txt')
